### PR TITLE
UPDATE

### PR DESCRIPTION
**Pull request by gutris1**
- Fix reading of non-ASCII chars in PNG parameters by using ExifReader js library.
- Fix JavaScript getting stuck on the first attempt.

### CODE REVIEW

**Comment by w-e-w** [comment]
just so you know when possible we don't like to change the url of a extension on the index
the reason being changing the URL only changes it for new installations
and based on NoCrypt account activity he is still active just last week
so in this case it's best to be contact the original repository

---

- Oops I meant to post this at https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/312#issuecomment-2103308732

**Comment by NoCrypt** [comment]
Okay, first of all im sorry that I didnt maintain most of my repo nowadays. It's beacuse I'm kinda busy with my thesis and stuff. As for this PR, I can re-open and merge it, plus giving you full access to maintain it if you want @gutris1

Again im so sorry

**Comment by gutris1** [comment]
> Okay, first of all im sorry that I didnt maintain most of my repo nowadays. It's beacuse I'm kinda busy with my thesis and stuff. As for this PR, I can re-open and merge it, plus giving you full access to maintain it if you want @gutris1
> 
> Again im so sorry

yes give me, I'll handle the merge

**Comment by NoCrypt** [comment]
@gutris1 done!

**Pull request merged**
