### PR TITLE
Simplify, Restore Raw pnginfo in HTML

### PR DESCRIPTION
**Pull request by w-e-w**
- Remove stylization formatting of HTML (Restore Raw pnginfo in HTML)

the output PNG info must not be formatted in a way that it will break the syntax
the user should be able to copy the output pnginfo and, the pnginfo syntax should be intact and parsable byweb UI

if you wish to add stylization formatting, only use colors / fonts / size
don't add new lines or extra text or even spaces or anything else that might break the syntax

alternatively (recommended) you could create a copy function and the copied output would be the raw text output (that is used in the send to copy past)
this way you can format the display however you like and no one would care

---

- massively simplify implementation

no need of the entire strange thing of using installer downloading `ExifReader` to  custom js dir then manually loading it via javascript, just pust stuff in jsvascript dir and let webui load it

making the reading of pnginfo into just one function call on image chagne
remove unnecessary bouncing of multiple / events

---

Note I have very little JavaScript experience, best thoroughly review the code

### CODE REVIEW

**Comment by w-e-w** [comment]
@gutris1

**Comment by gutris1** [comment]
> @gutris1

I dont format the RAW output, and the copy function always use the RAW output from geninfo Textbox
the html styling is just for an eye candy
just like default png info from webui, the raw text is hidden behind the HTML, that's what I learned from webui png info. 

I agree with the simplicity tho
but I can't with removing the HTML display

also removing the image from gr.Image
should return the output to null

I'll wait @NoCrypt to do the judge

**Comment by w-e-w** [comment]
> I dont format the RAW output, and the copy function always use the RAW output from geninfo Textbox
the html styling is just for an eye candy
just like default png info from webui, the raw text is hidden behind the HTML, that's what I learned from webui png info.

you are missing my point that I'm trying to make

like I mentioned above you either need a method to allow user to have direct access to the raw data
or you have to display the raw data
sending the info behind the scene to the tab is not the only use of this extension

somethinkg a copy button could be implemented simply in few lines of code
deciding where to put the button is the harder part

if you have a copy button or something similer you can do all the formatting you want
you can even do something in advance like https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/317#issuecomment-2119340787

Aesthetics should not come at the cost of functionality

---

in this PR my aim is to only simplify lots of non necessary code and do the minimum to restore its functionality
that's why I only remove the html formatting and not add new features
what functionality you decide to add later on it's up to you

**Comment by NoCrypt** [comment]
I think @w-e-w is right, people didnt use this extension for their own webui, they could also use this for sharing info quickly.

@gutris1, We can add back the HTML eye-candy later along with a functional button to copy the raw data. OR we can make raw data semi visible by using accordion.

**Pull request merged**
